site_name: Patched Atlas

theme:
  name: terminal
  palette: gruvbox_dark
  custom_dir: overrides
  features:
    - navigation.side.hide
    - navigation.top.cursor_animation.hide
    - navigation.side.toc.hide

#plugins:
#   - search
#   - awesome-nav

nav:
- Index: index.md
- About: about.md
- Blog: blog/index.md
- Book: book.md
- Podcast: podcast/episodes.md

site_url: https://patchedatlas.com
